name: Docker Build and Push (Linux)

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: &openmp_matrix
      fail-fast: false
      matrix:
        include:
          - folder: open.mp-latest-linux-386
            tag: linux-386
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Linux image and save as docker-archive tar
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.folder }}
          file: ${{ matrix.folder }}/Dockerfile
          push: false
          platforms: linux/386
          tags: michaelace/open.mp:${{ matrix.tag }}
          outputs: type=docker,dest=open.mp-docker-${{ matrix.tag }}.tar
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Upload built Linux image artifact
        uses: actions/upload-artifact@v4
        with:
          name: open.mp-docker-${{ matrix.tag }}.tar
          path: open.mp-docker-${{ matrix.tag }}.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    # Reusing the same matrix as the build job to ensure we push the correct tags
    strategy: *openmp_matrix
    steps:
      - name: Download built Linux image artifact
        uses: actions/download-artifact@v4
        with:
          name: open.mp-docker-${{ matrix.tag }}.tar
          path: .

      - name: Load Linux image
        run: docker load -i open.mp-docker-${{ matrix.tag }}.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Linux image tags
        run: docker push michaelace/open.mp:${{ matrix.tag }}
